### PR TITLE
Added support for icons in tabs

### PR DESCRIPTION
**Pull request by pohodnya**

### CODE REVIEW

**Comment by iRoachie** [comment]
@pohodnya Hey man thanks for the PR. Could you make the changes to the actual typescript instead of the build folder?. The project source is in typescript, thats compiled down to JS for people to use.

**Comment by iRoachie** [comment]
Also maybe instead of restricting it to Ionicons, we could let them pass in their own Icon component

**Comment by pohodnya** [comment]
Add support of all icon sets from react-native-vector-icons

**Comment by iRoachie** [comment]
Looks great @pohodnya, I will change over the library from TS to js today. 

Also instead of passing in an iconSet array, we could pass in an array of objects.

```jsx
 <MaterialTabs icons={[{icon: 'closed', iconSet: 'MaterialIcons']}/>
```

That way we don't duplicate

**Comment by iRoachie** [comment]
Hey @pohodnya I just completed the switch from typescript to normal js and flow. You'll need to rebase

**Pull request closed without merging**
